version: "3"
services:
  server-test:
    image: ghcr.io/lightcode5794/github-actions-playgound:latest
    build: .
    container_name: server-test
    restart: always
    ports:
      - 8004:8004
    # command: npm start
