version: "3"
services:
  server-test:
    image: ghcr.io/lightcode5794/github-actions-playgound:sha-82112da
    env_file:
      - .env
    build: .
    container_name: server-test
    restart: always
    ports:
      - ${PORT}:8004
    # command: npm start
